# GitHub Copilot Coding Agent Setup Steps
# This file configures the development environment for the Copilot coding agent
# See: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  # Install Node.js dependencies with npm caching
  - name: Install dependencies
    run: npm ci --legacy-peer-deps
    cache:
      # Cache node_modules to speed up subsequent runs
      paths:
        - node_modules
        - $HOME/.npm
      # Cache key includes OS and package-lock.json hash for consistency
      key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
      restore-keys: |
        ${{ runner.os }}-npm-
