import { insightService } from "src/insights/insightService";
import { UidProcessor } from 'src/insights/processors/UidProcessor';
import { VcardSyncPreProcessor } from 'src/insights/processors/VcardSyncPreProcessor';
import { RelatedOtherProcessor } from 'src/insights/processors/RelatedOtherProcessor';
import { RelatedFrontMatterProcessor } from 'src/insights/processors/RelatedFrontMatterProcessor';
import { RelatedListProcessor } from 'src/insights/processors/RelatedListProcessor';
import { VcardSyncPostProcessor } from 'src/insights/processors/VcardSyncPostProcessor';
import { GenderInferenceProcessor } from 'src/insights/processors/GenderInferenceProcessor';
import { GenderRenderProcessor } from 'src/insights/processors/GenderRenderProcessor';
import { RelatedNamespaceUpgradeProcessor } from 'src/insights/processors/RelatedNamespaceUpgradeProcessor';

insightService.register(UidProcessor);
insightService.register(VcardSyncPreProcessor);
insightService.register(RelatedOtherProcessor);
insightService.register(RelatedFrontMatterProcessor);
insightService.register(RelatedListProcessor);
insightService.register(VcardSyncPostProcessor);
insightService.register(GenderInferenceProcessor);
insightService.register(GenderRenderProcessor);
insightService.register(RelatedNamespaceUpgradeProcessor);
