import { insightService } from "src/insights/insightService";
import { UidProcessor } from 'src/insights/processors/uidValidate';
import { VcardSyncPreProcessor } from 'src/insights/processors/vcardSyncRead';
import { RelatedOtherProcessor } from 'src/insights/processors/relatedOther';
import { RelatedFrontMatterProcessor } from 'src/insights/processors/relatedFrontMatter';
import { RelatedListProcessor } from 'src/insights/processors/relatedList';
import { GenderInferenceProcessor } from 'src/insights/processors/genderInference';
import { GenderRenderProcessor } from 'src/insights/processors/genderRender';
import { RelatedNamespaceUpgradeProcessor } from 'src/insights/processors/namespaceUpgrade';
import { VcardSyncPostProcessor } from 'src/insights/processors/vcardSyncWrite';

insightService.register(UidProcessor);
insightService.register(VcardSyncPreProcessor);
insightService.register(RelatedOtherProcessor);
insightService.register(RelatedFrontMatterProcessor);
insightService.register(RelatedListProcessor);
insightService.register(RelatedNamespaceUpgradeProcessor);
insightService.register(GenderInferenceProcessor);
insightService.register(GenderRenderProcessor);
insightService.register(VcardSyncPostProcessor);
